//首页的栏目可以自己设置标题名称和图片，key不用改动，是列表页的识别标志，每个栏目的顺序也可以随意排序。
{"Home": [
{"key":"APP","title":"APP调试","pic":"https://epg.112114.xyz/bingimg"},
{"key":"网页","title":"网页调试","pic":"https://pic1.zhimg.com/v2-0863b14a3c54722f95148cb536ce49b0_b.jpg"},
{"key":"采集","title":"采集调试","pic":"https://pic1.zhimg.com/v2-1c7efe59fc035c67db278cb37c1908ac_b.jpg"},
{"key":"直播","title":"直播调试","pic":"https://pic4.zhimg.com/v2-ba98dc3c31c891a9d69ccbf45b07a107_b.jpg"},
{"key":"历史","title":"历史记录","pic":"https://pic4.zhimg.com/v2-544a06af71a0de850ae21432d277f5cf_b.jpg"},
{"key":"收藏","title":"我的收藏","pic":"https://pic3.zhimg.com/v2-71daae9a4aef25ce7a01606571b2365a_b.jpg"},
{"key":"推送","title":"远程推送","pic":"https://pic3.zhimg.com/v2-f9cad62fcd47b79e7345f2bcf49b281e_b.jpg"},
{"key":"待添加","title":"待添加","pic":"https://pic1.zhimg.com/v2-e77da20418dc6cf1b534ac030705a6fc_b.jpg"}
//{"key":"APP","title":"APP调试","pic":"https://epg.112114.xyz/bingimg"},
//{"key":"网页","title":"网页调试","pic":"https://epg.112114.xyz/bingimg"},
//{"key":"采集","title":"采集调试","pic":"https://epg.112114.xyz/bingimg"},
//{"key":"直播","title":"直播调试","pic":"https://epg.112114.xyz/bingimg"},
//{"key":"历史","title":"历史记录","pic":"https://epg.112114.xyz/bingimg"},
//{"key":"收藏","title":"我的收藏","pic":"https://epg.112114.xyz/bingimg"},
//{"key":"推送","title":"远程推送","pic":"https://epg.112114.xyz/bingimg"},
//{"key":"待添加","title":"待添加","pic":"https://epg.112114.xyz/bingimg"}
],

//填写APP接口，支持以下5种接口格式。
//{"name":"填接口名称","url":"http://xxx/api.php/v1.vod"},
//{"name":"填接口名称","url":"https://xxx/xgapp.php/v1/"},
//{"name":"填接口名称","url":"http://xxx/api.php/app/"},
//{"name":"填接口名称","url":"https://xxx/xgapp.php/v2/"},
//{"name":"填接口名称","url":"http://xxx/mogai_api.php/v1.vod"}
"zhuyejiekou": [
{"name":"手指影院","url":"https://szys5678.com/mogai_api.php/v1.vod"},
{"name":"零刻影院","url":"https://ys.ling00.cn/api.php/v1.vod"},
{"name":"益达影院","url":"http://luobu.yss6080.com/mogai_api.php/v1.vod"},
{"name":"全网影视","url":"http://zjr.jurentiaodeng.com/api.php/v1.vod"},
{"name":"蒲公英视频","url":"http://www.pgy1.top/ruifenglb_api.php/v1.vod"},
{"name":"阿里影视","url":"http://aliys.cn:90/api.php/v1.vod"},
{"name":"69美剧","url":"https://www.69mj.com/api.php/v1.vod"},
{"name":"特狗影视","url":"https://www.tegouys.com/xgapp.php/v2/"},
{"name":"独播社","url":"http://35ys.cc/api.php/v1.vod"},
{"name":"钟特影视","url":"https://app.zteys.com/api.php/v1.vod"},
{"name":"天空影视","url":"https://www.tkys.tv/xgapp.php/v2/"},
{"name":"神马影院","url":"https://www.smdyy.cc/api.php/app/"},
{"name":"913e影视","url":"http://www.913e.net/xgapp.php/v1/"},
{"name":"UU美剧","url":"https://www.uumjw.com/api.php/v1.vod"},
{"name":"vip影院","url":"http://360yy.cn/api.php/app/"},
{"name":"万能影院","url":"http://app.wnvod.net/lvdou_api.php/v1.vod"},
{"name":"三日影院","url":"https://www.3ri.net/api.php/v1.vod"},
{"name":"优视影视","url":"http://app.ysys.asia/lvdou_api.php/v1.vod"},
{"name":"兔子窝","url":"http://cj.huimaojia.com:12345/mogai_api.php/v1.vod"},
{"name":"创意影视","url":"https://www.30dian.cn/api.php/v1.vod"},
{"name":"双鹿影院","url":"http://cr.slidc.top/mubai_api.php/m2.vod"},
{"name":"嗷呜视频","url":"http://www.cx99999.cn/lvdou_api.php/v1.vod"},
{"name":"天天影视","url":"http://app.qianju.cc/api.php/v1.vod"},
{"name":"奈飞中文","url":"https://www.naifei.org/api.php/v1.vod"},
{"name":"开尔影院","url":"https://appx.uy07.com/api.php/v1.vod"},
{"name":"快云影音","url":"https://www.kuaiyunyy.com/api.php/app/"},
{"name":"恒大影视","url":"https://www.hdys.org/api.php/v1.vod"},
{"name":"暖光影视","url":"https://app.bl210.com/api.php/v1.vod"},
{"name":"月儿影视","url":"https://yue52.xyz/api.php/v1.vod"},
{"name":"橘子影视","url":"http://jz.juzidy.vip/mogai_api.php/v1.vod"},
{"name":"次元动漫","url":"http://81.68.211.181/lvdou_api.php/v1.vod"},
{"name":"瑞丰影视","url":"http://121.204.249.135:4433/ruifenglb_api.php/v1.vod"},
{"name":"比邻影视","url":"http://0hzy.cn:9990/mogai_api.php/v1.vod"},
{"name":"海胆影视","url":"http://xf123.cc/api.php/app/"},
{"name":"淘剧社","url":"https://app.shuhai99.com/api.php/v1.vod"},
{"name":"熊猫视频","url":"http://anegh.com/lvdou_api.php/v1.vod"},
{"name":"爱酷影视","url":"https://www.zhanlangbu.com/ruifenglb_api.php/v1.vod"},
{"name":"百淘影视","url":"http://ys.58g8.com/lvdou_api.php/v1.vod"},
{"name":"美剧范","url":"http://ttzmz.net/api.php/v1.vod"},
{"name":"美剧虫","url":"https://meijuchong.com/api.php/v1.vod"},
{"name":"躺平影视","url":"http://www.lltpys.com/api.php/app/"},
{"name":"追剧达人","url":"https://www.zhuijudaren.com/mogai_api.php/v1.vod"},
{"name": "9e国语","url": "http://vod.9e03.com/lvdou_api.php/v1.vod"},
{"name":"黄河影视","url":"http://i.ledu8.cn/api.php/v1.vod"},
{"name":"我爱跟剧","url":"https://www.genmov.com/mogai_api.php/v1.vod"},
{"name":"南府影视","url":"http://iapp.nfuxs.club/nfuxs.php/v1.vod"}, 
{"name":"影视大全","url":"http://app.269w.com/api.php/v1.vod"},
{"name":"影视大全2","url":"https://app.okmedcos.com/api.php/v1.vod"},
{"name":"天空影视","url":"https://tkys.tv/xgapp.php/v1/"},
{"name":"QC影视","url":"https://www.qcsvip.com/mogai_api.php/v1.vod"}, 
{"name":"影库","url":"https://yingkudy.com/lvdou_api.php/v1.vod"},
{"name":"OK影视","url":"http://123.ok00.xyz/api.php/v1.vod"},
{"name":"粉象视界","url":"http://42.157.129.15:34444/lvdou_api.php/v1.vod"},
{"name":"爱电影","url":"https://www.idianying.com.cn/mogai_api.php/v1.vod"},
{"name":"冷视TV","url":"https://len.tv/api.php/v1.vod"},
{"name":"迪迪影院","url":"http://dd88.icu:6080/xgapp.php/v2/"},
{"name":"段友影视","url":"https://shangjihuoke.com/api.php/tv.vod"},
{"name":"段友影视2","url":"http://js.66app.me/api.php/app/"},
{"name":"渔渔影视","url":"http://luobo.yugenye.site/api.php/v1.vod"},
{"name":"MX影视","url":"http://mkk.gotka.top/api.php/v1.vod"},
{"name":"艾特影视","url":"https://www.aitee.cc/api.php/v1.vod"},
{"name":"看剧吧","url":"http://app.ishen520.com/api.php/v1.vod"}],


//填写采集接口
"caijizhan": [
{"name":"AV6888资源站","url":"http://m.7777688.com/inc/apijson.php"},
{"name":"老鸭TV","url":"https://laoyatv.com/api.php"},
{"name":"爱播资源","url":"https://cj.apiabzy.com/api.php"},
{"name":"酷豆资源","url":"https://api.kdapi.info/api.php"},
{"name":"芒果资源","url":"https://mgzyz1.com/api.php"},
{"name":"丝袜资源","url":"https://siwazyw.cc/api.php"},
{"name":"水蜜桃","url":"https://51smt4.xyz/api.php"},
{"name":"色窝资源","url":"https://sewozyapi.com/api.php"},
{"name":"淫窝资源","url":"https://api.yinwoapi.com/api.php"},
{"name":"佳丽资源","url":"https://jializyzapi.com/api.php"},
{"name":"老鸭资源","url":"https://api.apilyzy.com/api.php"},
{"name":"秀色资源","url":"https://api.xiuseapi.com/api.php"},
{"name":"探探资源","url":"https://apittzy.com/api.php"},
{"name":"99资源","url":"http://99zy.pw/api.php"},
{"name":"麻豆视频","url":"https://madouse.la/api.php"},
{"name":"91麻豆","url":"https://91md.me/api.php"},
{"name":"花椒资源","url":"https://apihjzy.com/api.php"},
{"name":"辣椒资源","url":"https://apilj.com/api.php"},
{"name":"乐播资源","url":"https://lbapi9.com/api.php"},
{"name":"CK资源","url":"https://ckzy.me/api.php"},
{"name":"鲨鱼资源","url":"https://shayuapi.com/api.php"},
{"name":"卧龙资源","url":"https://collect.wolongzyw.com/api.php"},
{"name":"天空资源网","url":"https://api.tiankongapi.com/api.php"},
{"name":"鱼乐资源","url":"https://api.yulecj.com/api.php"},
{"name":"鱼乐资源2","url":"https://api.ylzy1.com/api.php"},
{"name":"红牛资源","url":"https://www.hongniuzy2.com/api.php"},
{"name":"酷点资源","url":"https://kudian10.com/api.php"},
{"name":"酷点资源2","url":"https://kudianzy.com/api.php"},
{"name":"想看资源","url":"https://m3u8.xiangkanapi.com/api.php"},
{"name":"速更资源","url":"https://www.sugengzy.cn/api.php"},
{"name":"KK资源","url":"https://kkzy.me/api.php"},
{"name":"飞速资源","url":"https://www.feisuzyapi.com/api.php"},
{"name":"百度云资源","url":"https://api.apibdzy.com/api.php"},
{"name":"U酷资源","url":"https://api.ukuapi.com/api.php"},
{"name":"樱花资源","url":"https://m3u8.apiyhzy.com/api.php"},
{"name":"光速资源","url":"https://api.guangsuapi.com/api.php"},
{"name":"FOX资源","url":"https://api.foxzyapi.com/api.php"},
{"name":"快播云","url":"http://www.kuaibozy.com/api.php/"},
{"name":"人人资源","url":"https://www.rrzyw.cc/api.php"},
{"name":"U猫","url":"http://umao.ml/api.php/"},
{"name":"1905资源","url":"http://zy.yilans.net:8090/api.php"},
{"name":"M3U8.TV","url":"http://www.zycaiji.net:7788/api.php"},
{"name":"番茄影院","url":"http://api.fqzy.cc/api.php"},
{"name":"39影视","url":"https://www.39kan.com/api.php"},
{"name":"播放吧","url":"https://www.bofangya.com/api.php/"},
{"name":"七七","url":"http://api.kunyu77.com/api.php"},
{"name":"77电影","url":"https://www.77diany.com/api.php"},
{"name":"789盘","url":"https://www.rrvipw.com/api.php"},
{"name":"TVB云播","url":"http://www.tvyb02.com/api.php"},
{"name":"一拳动漫","url":"http://47.97.68.224/api.php"},
{"name":"乐活资源","url":"https://lehootv.com/api.php"},
{"name":"千寻时光","url":"http://wy.dqyhg.cn/api.php"},
{"name":"嗨哆咪影视","url":"http://hdmys1.com/api.php"},
{"name":"天堂资源","url":"http://vipmv.cc/api.php"},
{"name":"天天看","url":"https://www.ttky8.com/api.php"},
{"name":"小猫咪","url":"http://zy.xiaomaomi.cc/api.php"},
{"name":"忆梦","url":"http://anltv.cn/api.php"},
{"name":"思古影院","url":"https://www.siguyy.net/api.php"},
{"name":"新浪资源","url":"http://api.xinlangapi.com/xinlangapi.php"},
{"name":"旋风云","url":"http://appimg.ssxmall.cn/api.php"},
{"name":"松鼠资源","url":"https://m3u8.songshuzy.com/api.php"},
{"name":"橘子影视","url":"http://jz.juzidy.vip/api.php"},
{"name":"橘猫影视","url":"http://www.zitv.cc/api.php"},
{"name":"段友影视","url":"http://shangjihuoke.com/api.php"},
{"name":"江北资源","url":"https://gfzycj.hnmj.vip/api.php"},
{"name":"海外电影","url":"https://www.200121.com/api.php"},
{"name":"畅视影视","url":"http://app.reboju.net/api.php"},
{"name":"看猫","url":"http://124.222.83.15:88/api.php"},
{"name":"神速资源","url":"https://api.sszyapi.com/api.php"},
{"name":"考拉TV","url":"https://ikaola.tv/api.php"},
{"name":"胖猫影视","url":"http://www.pangmaotv.com/api.php"},
{"name":"诺讯资源","url":"http://caiji.nxflv.com/api.php"},
{"name":"酷猫影视","url":"https://www.pgcms10.com/api.php"},
{"name":"飘花电影","url":"http://www.zzrhgg.com/api.php"},
{"name":"if101","url":"https://demo.if101.tv/api.php"},
{"name":"苹果采集","url":"http://107.150.5.146:39000/maccms10-main/api.php"},
{"name":"特狗影视","url":"http://tv.tegouys.com/api.php/iptv/vod/"},
{"name":"推荐采集","url":"http://101.34.7.151:600/api.php"},
{"name":"wabc(腾讯直采)","url":"https://wabc.ml/mao/1.php"},
{"name":"wabc(爱奇艺直采)","url":"https://wabc.ml/mao/2.php"},
{"name":"木子看剧","url":"https://mzkj.maccms.cf/api.php"},
{"name":"阿远采集","url":"https://www.cjzy.xyz:8888/api.php"},
{"name":"金鹰资源","url":"http://jinyingzy.com/provide/vod"},
{"name":"快车资源","url":"https://caiji.kczyapi.com/api.php"},
{"name":"多多资源","url":"https://www.ddzyz1.com/api.php"},
{"name":"OK资源","url":"https://www.okcj.site/api"},
{"name":"量子资源","url":"http://cj.lziapi.com/api.php"},
{"name":"闪电资源","url":"http://sdzyapi.com/api.php"},
{"name":"无尽资源","url":"https://wujinzy.net/api.php"},
{"name":"南国影源","url":"http://api.nguonphim.tv/api.php"},
{"name":"看看资源","url":"https://zy.hikan.xyz/api.php"},
{"name":"奈菲迷","url":"https://app.netflixmi.com/ruifenglb_api.php"},
{"name":"XYUI","url":"http://jx4.xyui.top:7001/api.php"},
{"name":"ASMR","url":"http://www.asmr19.in/api.php"},
{"name":"51看剧","url":"http://51kanju.cn/api.php"},
{"name":"天天影视","url":"http://tt2022.ga/api.php"},
{"name":"超高清影视","url":"http://shdmv.com/api.php"},
{"name":"趣看","url":"https://qkmp4.cn/api.php"},
{"name":"快看客栈","url":"https://www.vp1127.com/api.php"},
{"name":"网民电影","url":"https://www.prinevillesda.org/api.php"},
{"name":"影视阁","url":"http://216.98.10.85/api.php/iptv/vod/"},
{"name":"小南TV","url":"http://n293.ngys.xyz/mv/api.php/Chengcheng/vod/"},
{"name":"天空TV","url":"http://tv.tkys.tv/api.php/iptv/vod/"},
{"name":"芒迅TV","url":"http://www.hdyangtv.com/api.php/iptv/vod/"},
{"name":"米来影视","url":"http://42.51.37.161:2346/api.php/iptv/vod/"},
{"name":"金叶影院","url":"http://r.zjj.life:88/mv/api.php/Chengcheng/vod/"},
{"name":"盒子视界","url":"http://eh.tvzy.cc/api.php/iptv/vod/"},
{"name":"嘿荼锋","url":"http://tv.hfys8.vip/api.php/Sntv/vod/"},
{"name":"贵宾影院","url":"https://vipdytv.com/api.php/iptv/vod/"},
{"name":"猫咪影院","url":"http://cms.feifan12.xyz/api.php/iptv/vod/"},
{"name":"独优影视","url":"http://121.205.88.71:218/api.php/Chengcheng/vod/"},
{"name":"CV影视","url":"http://www.cccvvv.top/api.php/iptv/vod/"},
{"name":"2号币","url":"http://phoebe.cf/api.php/iptv/vod/"},
{"name":"1080资源库","url":"https://api.1080zyku.com/inc/api_mac10.php/"}],


//主解析是JSON直链格式的解析
"zhujiexi":[
{"name":"293","url":"http://81.71.48.249:4456/jsonc/longxia.php?url="},
{"name":"线路NX","url":"https://vip.nxflv.com/home/api?uid=701203&key=bltuyCEFKLTX013679&url="},
{"name":"leduo","url":"https://api.ldjx.cc/wp-api/getvodurl.php?token=1001&vid="},
{"name":"renrenmi2","url":"https://a.dxzj88.com/jxrrm/jiami.php?url="},
{"name":"renrenmi3","url":"https://sz.dxzj88.com/jxrjrm/jiaomi.php?url="},
{"name":"2","url":"https://jx.mczdyw.com/xg.php?url="},
{"name":"3","url":"https://www.aiaine.com/api/?key=kVqmG5dAQ5dZTcECw8&url="},
{"name":"4","url":"https://svip.rongxingvr.top/api/?key=niBgMGXVdCQhsmeEBK&url="},
{"name":"8","url":"https://app.iminna.com/jx/?url="},
{"name":"飓风影院2","url":"https://vvip.funsline.cn/api/?key=3xWfEoDf4V9p9Y20CR&url="},
{"name":"我爱电影网","url":"https://jhpc.manduhu.com/j1217.php?url="},
{"name":"江湖解析","url":"http://103.40.240.46/jh/?url="},
{"name":"王牌","url":"https://za.kuanjv.com/?url="},
{"name":"盘古解析","url":"https://json.pangujiexi.com:12345/json.php?url="},
{"name":"欢雨","url":"http://www.youhuifuligou.com/json/?id=7&url="},
{"name":"久九影视","url":"https://json.hfyrw.com/mao.go?url="},
{"name":"aiaine02","url":"https://vip.aiaine.com/api/?key=8FN8gNAySnvJiMllxZ&url="},
{"name":"五一解析","url":"https://json.5lp.net/json.php?url="},
{"name":"RongXingVR","url":"https://vip.rongxingvr.top/api/?key=JJEZkZIhzkA4cUtBfR&url="},
{"name":"J13","url":"https://languangyingshiziyuan.1080zy.top/longtengzy.php/?url="},
{"name":"Wuduzy","url":"https://aa.xkys.tv/json.php?url="},
{"name":"LTRX","url":"https://svip.spchat.top/api/?type=ys&key=bKemW41JnxmQb4l67h&url="},
{"name":"喵派对资源3","url":"https://vip.aiaine.com/api/?key=fOWaGgFU45zlIjvbHI&url="},
{"name":"喵派对资源2","url":"https://svip.iremind.me/api/?key=A5Db8HF8c8FSIOR6R1&url="},
{"name":"leduotv","url":"https://api.leduotv.com/wp-api/getvodurl.php?vid="},
{"name":"蓝光视频","url":"https://api.m3u8.tv:5678/home/api?type=ys&uid=1931000&key=gktuvyzABEORSYZ135&url="},
{"name":"绿箭影视","url":"https://api.m3u8.tv:5678/home/api?type=ys&uid=7743764&key=acgjlopuxACEHJLT48&url="},
{"name":"筋斗云","url":"https://api.m3u8.tv:5678/home/api?type=ys&uid=1494542&key=ijmqvwxABEHILMOT48&url="},
{"name":"jx36","url":"https://api.m3u8.tv:5678/home/api?type=ys&uid=9105801&key=huwxFGILMOQSTUZ679&url="},
{"name":"DC影视","url":"https://api.m3u8.tv:5678/home/api?type=ys&uid=7665652&key=dglmnwEFILMOPRW056&url="},
{"name":"4K影院1","url":"https://api.m3u8.tv:5678/home/api?type=ys&uid=1095368&key=cdgjpsuDFLNRTUVY03&url="},
{"name":"益达影院","url":"https://api.m3u8.tv:5678/home/api?type=ys&uid=123503&key=fgkqryzDEFLNQSTW69&url="},
{"name":"影阅阁","url":"https://api.m3u8.tv:5678/home/api?type=ys&uid=594615&key=bcehpqtxCEGKMT0248&url="},
{"name":"小强TV","url":"https://api.m3u8.tv:5678/home/api?type=ys&uid=867242&key=acjksAGHJMPQTY3567&url="},
{"name":"瑞丰","url":"https://api.m3u8.tv:5678/home/api?type=ys&uid=1285201&key=bcikqtwxyADEGKUX36&url="},
{"name":"抹茶猪","url":"https://api.m3u8.tv:5678/home/api?type=ys&uid=1525223&key=fhikpsvBCDFHJOSUZ8&url="},
{"name":"zhujiexi1","url":"https://api.witjia.com/json.php?key=HhDgMmjiHz0BaF5IJh&url="},
{"name":"zhujiexi2","url":"https://www.x-n.cc/api.php?url="},
{"name":"zhujiexi3","url":"https://tv.yjhan.com/cljson3394/?url="},
{"name":"zhujiexi4","url":"https://jx.xiaoysw1.com/appjson/1.php?url="},
{"name":"zhujiexi5","url":"http://47.100.138.210:91/home/api?type=ys&uid=2086844&key=ajklotxzAGIJPSVX14&url="}],


//备用解析是常规格式的解析
"beiyongjiexi": [
{"name":"OJBK","url":"https://jmwl.qd234.cn/v/?v="},
{"name":"M117","url":"http://1.117.152.239:39000/?url="},
{"name":"zui","url":"https://jx.zui.cm/?url="},
{"name":"parwix1","url":"https://jx.parwix.com:4433/player/?url="},
{"name":"parwix2","url":"https://jx.parwix.com:4433/player/analysis.php?v="},
{"name":"xuerenweb","url":"https://s.2tu.uk/?url="},
{"name":"xuerenweb2","url":"https://xrm3u8.qd234.cn/?url="},
{"name":"美剧虫","url":"https://jx.daiguaji.com/?url="},
{"name":"miao","url":"https://jx.58g8.com/1/?url="},
{"name":"万能解析","url":"https://vip.legendwhb.cn/m3u8.php?url="},
{"name":"ltnb04","url":"https://vip.bljiex.com/?v="},
{"name":"CL4K01","url":"https://ys.ling00.cn/CL4K/?url="},
{"name":"CL4K02","url":"https://app.okmedcos.com/4k/?url="},
{"name":"解析02","url":"http://jf.tcspvip.com:246/home/api?type=ys&uid=65404&key=bjoprtvyABGIMPXZ27&url="},
{"name":"解析03","url":"http://jx.ledu8.cn/api/?key=P8QSgO61p1MpHV2ALn&url="},
{"name":"解析12","url":"https://api.parwix.com:4433/analysis/json/?uid=1735&my=cejkmnuvyBEFINR056&url="},
{"name":"解析14","url":"https://supervip.rongxingvr.cn:8866/api/?key=nKn4eO8giUKSe8jxZU&url="},
{"name":"解析15","url":"https://json.legendwhb.cn/json.php/?url="},
{"name":"解析16","url":"https://xt.gbxy.net.cn/api/?key=7gAmfK5typSVsg2Qnr&url="},
{"name":"解析17","url":"http://14.17.115.200:520/json.php?id=6e5LaYyU5JLs9aRawyGKwPkH7ZFr701z&url="},
{"name":"解析18","url":"http://newjiexi.gotto.top/yun_apib.php/?url="},
{"name":"解析19","url":"http://ccc.ysys.asia/jx/?id=2&url="},
{"name":"解析20","url":"http://vipjh.chunbaotaiji.com/?url="},
{"name":"解析21","url":"https://jhjx.ptygx.com/xttyjx.php/?url="},
{"name":"解析22","url":"https://api.zakkpa.com:8888/analysis/json/?uid=39&my=ehklrtxzAFKLMNUXY2&url="},
{"name":"解析23","url":"http://fast.rongxingvr.cn:99/api/?key=M3tZzS2q0oGrQ7aWlr&url="},
{"name":"解析24","url":"http://jf.jisutuku.top/api/?key=RHjXcjUTkyZnfWx9u4&url="},
{"name":"解析25","url":"https://vip.kpjx.cc/api/?key=3sKKYzWSxLmX1hnsMs&url="},
{"name":"解析26","url":"http://47.100.138.210:91/home/api?type=ys&uid=1947441&key=bcfgjmuwCEORSVX237&url="},
{"name":"解析27","url":"https://fast.rongxingvr.cn:8866/api/?key=rmxOw7BpINuGIyWQng&url="},
{"name":"解析28","url":"https://fast.rongxingvr.cn:8866/api/?key=nrR7koAyq9ajKId4nC&url="},
{"name":"解析29","url":"http://a.dxzj88.com/jhjson/?url="},
{"name":"解析30","url":"https://fast.rongxingvr.cn:8866/api/?key=J4mUIu3DrRtIOojDox&url="},
{"name":"解析32","url":"http://47.100.138.210:91/home/api?type=ys&uid=243653&key=kqswxyABGHKLQSV127&url="},
{"name":"解析33","url":"https://fast.rongxingvr.cn:8866/api/?key=jtDZ22biNujOBLlgoe&url="},
{"name":"解析34","url":"http://ccc.ysys.asia/jx/?id=4&url="},
{"name":"解析36","url":"https://jhjx.ptygx.com/xttyjx.php/?url="},
{"name":"解析37","url":"https://sbsb.i8k.cc/?url="},
{"name":"解析38","url":"http://gq.bywdtk.cn/?url="},
{"name":"解析39","url":"https://balabala.yatongle.com/api/?key=RuHZpg9zxigiLZRIyl&url="},
{"name":"解析40","url":"http://jx.ledu8.cn/api/?key=P8QSgO61p1MpHV2ALn&url="},
{"name":"解析41","url":"https://api.zakkpa.com:8888/analysis/json/?uid=39&my=bdfinvyBCDEJKUY089&url="},
{"name":"解析42","url":"https://jx.renrenmi.cc/?url="},
{"name":"萌蛋蛋","url":"https://svip.renrenmi.cc:2222/api/?key=LorFAswZzr3sGNI0YU&url="},
{"name":"影阅阁2","url":"https://svip.renrenmi.cc:2222/api/?key=82KErJogweliHPt7Yp&url="},
{"name":"看剧吧","url":"https://svip.renrenmi.cc:2222/api/?key=fI3YQ3vxF5uREfNpDU&url="},
{"name":"麻瓜视频","url":"https://api.parwix.com:4433/analysis/json/?uid=1735&my=egkqvxzBEHPQSUWX28&url="},
{"name":"南府影视","url":"http://play.szbodankyy.com/cnmb111/?url="},
{"name":"雨果影视","url":"http://103.40.246.5:6881/ijsonononxxt/?url="},
{"name":"艾特影视","url":"http://159.75.45.225:12588/?url="},
{"name":"追剧吧","url":"https://www.lengyue.app/hdsfajdkljlasjklsaj/?url="},
{"name":"Yoyo","url":"http://47.100.138.210:91/home/api?type=ys&uid=1947441&key=bcfgjmuwCEORSVX237&url="},
{"name":"追剧吧3","url":"http://47.100.138.210:91/home/api?type=ys&uid=715391&key=bdltvyACHKLQX01789&url="},
{"name":"阿姨追剧","url":"http://47.100.138.210:91/home/api?type=ys&uid=2867314&key=ntyzDEGHPQVW234789&url="},
{"name":"手指影视","url":"http://a.dxzj88.com/jhjson/?url="},
{"name":"二九影视","url":"http://47.94.137.151:8089/?url="},
{"name":"黄河影视","url":"http://jx.ledu8.cn/api/?key=P8QSgO61p1MpHV2ALn&url="},
{"name":"雨果影视1","url":"https://json.nbjx.vip:4399/?wap=0&url="},
{"name":"优视影视","url":"http://ccc.ysys.asia/jx/?id=2&url="},
{"name":"星影相随1","url":"https://xt.gbxy.net.cn/api/?key=7gAmfK5typSVsg2Qnr&url="},
{"name":"抹茶猪","url":"https://svip.renrenmi.cc:2222/api/?key=81gnuXCwZK9IZxt8bU&url="},
{"name":"筋斗云1","url":"https://fast.rongxingvr.cn:8866/api/?key=nrR7koAyq9ajKId4nC&url="},
{"name":"看剧吧1","url":"http://47.100.138.210:91/home/api?type=ys&uid=243653&key=kqswxyABGHKLQSV127&url="},
{"name":"麻瓜视频1","url":"https://jhjx.ptygx.com/xttyjx.php/?url="},
{"name":"看剧吧2","url":"https://fast.rongxingvr.cn:8866/api/?key=G0KF039jDQWlMHMf5z&url="},
{"name":"星辰视频","url":"https://cs.024zs.com:4433/api/?key=2yqrXys9F3TcDiRz3k&url="},
{"name":"阿姨追剧1","url":"https://cs.024zs.com:4433/api/?key=P3lAZ3QJlv6KBNNLHM&url="},
{"name":"爱影视","url":"http://json.iqtv.tv/json.php?id=syhdjjjelxu66&url="},
{"name":"影阅阁","url":"http://api1.json.vin:4433/api/?key=WPDh6vf0aT0ahepWzW&url="},
{"name":"瑞丰资源","url":"https://cs.024zs.com:4433/api/?key=BKJ8LHmu8n9SD4Tou7&url="},
{"name":"阿姨追剧3","url":"http://json.qd234.cn/home/api?type=ys&uid=353067&key=bghmnoxBIKORUV1269&url="},
{"name":"疯狂看","url":"https://a.zhuijula.top/yun_api.php?url="},
{"name":"Yoyo1","url":"https://json.legendwhb.cn/znjson.php/?url="},
{"name":"灵狐影视","url":"https://api.parwix.com:4433/analysis/json/?uid=84&my=gijkmnouvxyFHPYZ28&url="},
{"name":"Vip影院1","url":"https://api.zakkpa.com:8888/analysis/json/?uid=39&my=bdfinvyBCDEJKUY089&url="},
{"name":"无名","url":"https://api.zakkpa.com:8888/analysis/json/?uid=91&my=gjksuvCHIJLRS01268&url="},
{"name":"麻瓜","url":"https://api.parwix.com:4433/analysis/json/?uid=1735&my=cejkmnuvyBEFINR056&url="},
{"name":"追剧吧2","url":"https://svip.spchat.top/api/?key=SAl7tLs3Zzu5alSNtz&url="},
{"name":"看剧1","url":"https://supervip.rongxingvr.cn:8866/api/?key=nKn4eO8giUKSe8jxZU&url="},
{"name":"Yo1","url":"https://json.legendwhb.cn/json.php/?url="},
{"name":"爱影","url":"http://14.17.115.200:520/json.php?id=6e5LaYyU5JLs9aRawyGKwPkH7ZFr701z&url="},
{"name":"追剧吧1","url":"http://newjiexi.gotto.top/yun_apib.php/?url="},
{"name":"无名-1","url":"http://vipjh.chunbaotaiji.com/?url="},
{"name":"Vip影院","url":"https://api.zakkpa.com:8888/analysis/json/?uid=39&my=ehklrtxzAFKLMNUXY2&url="},
{"name":"大头影视","url":"http://fast.rongxingvr.cn:99/api/?key=M3tZzS2q0oGrQ7aWlr&url="},
{"name":"绿箭","url":"http://jf.jisutuku.top/api/?key=RHjXcjUTkyZnfWx9u4&url="},
{"name":"我爱电影1","url":"https://vip.kpjx.cc/api/?key=3sKKYzWSxLmX1hnsMs&url="},
{"name":"蜜果TV","url":"https://fast.rongxingvr.cn:8866/api/?key=rmxOw7BpINuGIyWQng&url="},
{"name":"麻花视频","url":"http://jf.tcspvip.com:246/home/api?type=ys&uid=65404&key=bjoprtvyABGIMPXZ27&url="},
{"name":"TV酷","url":"http://a.dxzj88.com/jhjson/?url="},
{"name":"饭后电影","url":"https://fast.rongxingvr.cn:8866/api/?key=J4mUIu3DrRtIOojDox&url="},
{"name":"看剧","url":"http://47.100.138.210:91/home/api?type=ys&uid=243653&key=kqswxyABGHKLQSV127&url="},
{"name":"豆渣影视","url":"https://fast.rongxingvr.cn:8866/api/?key=jtDZ22biNujOBLlgoe&url="},
{"name":"优视影视2","url":"http://ccc.ysys.asia/jx/?id=4&url="},
{"name":"星空影视","url":"http://api.vip123kan.vip/?url="},
{"name":"爱追剧","url":"https://jhjx.ptygx.com/xttyjx.php/?url="},
{"name":"极客","url":"https://sbsb.i8k.cc/?url="},
{"name":"遗忘影视","url":"http://gq.bywdtk.cn/?url="},
{"name":"玺娜影视","url":"https://balabala.yatongle.com/api/?key=RuHZpg9zxigiLZRIyl&url="},
{"name":"林谷影视","url":"http://jf.lemiaoyun.cn/home/api?type=ys&uid=40190120&key=dhilnoCDHLOPQRUW29&url="},
{"name":"雪人影视","url":"https://svip.renrenmi.cc:2222/api/?key=S77lACKG9VTwNq5Upv&url="},
{"name":"json1","url":"http://admin.vodjx.top/json.php?url="},
{"name":"json2","url":"http://jx.vipmv.co/json3/?url="},
{"name":"json3","url":"http://jxgg.work/json.php?url="},
{"name":"json4","url":"http://play.bichangzw.cn/jianghu/json/?url="},
{"name":"json5","url":"http://yry.schdd.cn:81/csjson.php?url="},
{"name":"json6","url":"https://api.parwix.com:4433/analysis/json/?uid=654&my=abdeinruvxyBDORWX7&url="},
{"name":"json7","url":"https://json.iopenyun.com:33/cms_m3u8_api.php?url="},
{"name":"json8","url":"https://json.xiongmiao888.cn/?url="},
{"name":"json9","url":"https://vip.parwix.com:4433/analysis/json/?uid=2206&my=hmqwABCHILMNTV5678&url="},
{"name":"json10","url":"https://www.json.yihuiton.com/?url="},
{"name":"七哥","url":"https://jx.mmkv.cn/tv.php?url="},
{"name":"冰豆","url":"https://api.qianqi.net/vip/?url="},
{"name":"迪奥","url":"https://123.1dior.cn/?url="},
{"name":"CK","url":"https://www.ckplayer.vip/jiexi/?url="},
{"name":"LE","url":"https://lecurl.cn/?url="},
{"name":"ckmov","url":"https://www.ckmov.vip/api.php?url="},
{"name":"ccyjjd","url":"https://ckmov.ccyjjd.com/ckmov/?url="},
{"name":"RDHK","url":"https://jx.rdhk.net/?v="},
{"name":"爱豆","url":"https://jx.aidouer.net/?url="},
{"name":"h8","url":"https://www.h8jx.com/jiexi.php?url="},
{"name":"BL","url":"https://vip.bljiex.com/?v="},
{"name":"解析la","url":"https://api.jiexi.la/?url="},
{"name":"MUTV","url":"https://jiexi.janan.net/jiexi/?url="},
{"name":"MAO","url":"https://www.mtosz.com/m3u8.php?url="},
{"name":"老板","url":"https://vip.laobandq.com/jiexi.php?url="},
{"name":"盘古","url":"https://www.pangujiexi.cc/jiexi.php?url="},
{"name":"盖世","url":"https://www.gai4.com/?url="},
{"name":"小蒋","url":"https://www.kpezp.cn/jlexi.php?url="},
{"name":"YiTV","url":"https://jiexi.us/?url="},
{"name":"星空","url":"http://60jx.com/?url="},
{"name":"0523","url":"https://go.yh0523.cn/y.cy?url="},
{"name":"17云","url":"https://www.1717yun.com/jx/ty.php?url="},
{"name":"4K","url":"https://jx.4kdv.com/?url="},
{"name":"云析","url":"https://jx.yparse.com/index.php?url="},
{"name":"8090","url":"https://www.8090g.cn/?url="},
{"name":"江湖","url":"https://api.jhdyw.vip/?url="},
{"name":"PM","url":"https://www.playm3u8.cn/jiexi.php?url="},
{"name":"奇米","url":"https://qimihe.com/?url="},
{"name":"思云","url":"https://jx.ap2p.cn/?url="},
{"name":"听乐","url":"https://jx.dj6u.com/?url="},
{"name":"aijx","url":"https://jiexi.t7g.cn/?url="},
{"name":"夜幕","url":"https://www.yemu.xyz/?url="},
{"name":"52","url":"https://vip.52jiexi.top/?url="},
{"name":"黑米","url":"https://www.myxin.top/jx/api/?url="},
{"name":"豪华啦","url":"https://api.lhh.la/vip/?url="},
{"name":"凉城","url":"https://jx.mw0.cc/?url="},
{"name":"33t","url":"https://www.33tn.cn/?url="},
{"name":"180","url":"https://jx.000180.top/jx/?url="},
{"name":"无名1","url":"https://www.administratorw.com/video.php?url="},
{"name":"黑云","url":"https://jiexi.380k.com/?url="},
{"name":"九八","url":"https://jx.youyitv.com/?url="},
{"name":"综合线路解析","url":"https://www.showxi.xyz/mov/s/?sv=3&url="},
{"name":"纯净/B站","url":"https://z1.m1907.cn/?jx="},
{"name":"高速接口","url":"https://jsap.attakids.com/?url="},
{"name":"综合/B站1","url":"https://vip.parwix.com:4433/player/?url="},
{"name":"OK解析","url":"https://okjx.cc/?url="},
{"name":"乐多资源","url":"https://api.leduotv.com/wp-api/ifr.php?isDp=1&vid="},
{"name":"诺诺","url":"https://www.ckmov.com/?url="},
{"name":"全民","url":"https://jx.quanmingjiexi.com/?url="},
{"name":"M3U8","url":"https://jx.m3u8.tv/jiexi/?url="},
{"name":"大白","url":"https://api.myzch.cn/?url="},
{"name":"云点播","url":"https://api.iopenyun.com:88/vip/?url="},
{"name":"虾米","url":"https://jx.xmflv.com/?url="},
{"name":"沐白","url":"https://www.miede.top/jiexi/?url="},
{"name":"久播","url":"https://jx.jiubojx.com/vip.php?url="},
{"name":"SMYS","url":"https://jxx.smys8.cn/index.php?url="},
{"name":"明日","url":"https://jx.yingxiangbao.cn/vip.php?url="},
{"name":"维多","url":"https://jx.ivito.cn/?url="},
{"name":"星驰","url":"https://vip.cjys.top/?url="},
{"name":"66","url":"https://api.3jx.top/vip/?url="},
{"name":"116","url":"https://jx.116kan.com/?url="},
{"name":"200","url":"https://vip.66parse.club/?url="},
{"name":"月亮","url":"https://api.yueliangjx.com/?url="},
{"name":"小狼","url":"https://jx.yaohuaxuan.com/?url="},
{"name":"老鸭资源","url":"https://player.77lehuo.com/aliplayer/?url="},
{"name":"(无名)","url":"https://api.zakkpa.com:8888/analysis/json/?uid=91&my=gjksuvCHIJLRS01268&url="},
{"name":"麻瓜1","url":"https://api.parwix.com:4433/analysis/json/?uid=1735&my=cejkmnuvyBEFINR056&url="},
{"name":"Yoyo2","url":"https://json.legendwhb.cn/json.php/?url="},
{"name":"爱影视1","url":"http://14.17.115.200:520/json.php?id=6e5LaYyU5JLs9aRawyGKwPkH7ZFr701z&url="},
{"name":"黄河","url":"http://jx.ledu8.cn/api/?key=P8QSgO61p1MpHV2ALn&url="},
{"name":"(无名)1","url":"http://vipjh.chunbaotaiji.com/?url="},
{"name":"绿箭1","url":"http://jf.jisutuku.top/api/?key=RHjXcjUTkyZnfWx9u4&url="},
{"name":"雪人","url":"https://svip.renrenmi.cc:2222/api/?key=S77lACKG9VTwNq5Upv&url="},
{"name":"诺讯","url":"https://www.nxflv.com/?url="},
{"name":"beiyongjiexi","url":"https://nbjx.vip/?url="},
{"name":"beiyongjiexi1","url":"http://47.100.138.210:92/?url="},
{"name":"beiyongjiexi3","url":"http://ys.ling00.cn/json/?type=app&key=&url="},
{"name":"beiyongjiexi4","url":"http://ts.yjhan.com:8090/api/?type=app&key=DSQFgXdmj9xkDyiXdr&url="},
{"name":"renrenjiexi2","url":"https://analysis.yikan.one/analysis/player/?uid=8&my=fjkmoqFJLORTVZ1359&url="},
{"name":"renrenjiexi1","url":"http://leleys.xyz/app/csjx.php?url="},
{"name":"renrenjiexi","url":"https://jx.renrenmi.cc/?url="},
{"name":"LTjiexi","url":"https://ltjx.jeeves.vip/home/api?type=ys&uid=1136443&key=bhijopryzBJKLMSUX8&url="},
{"name":"LTjiexi1","url":"https://ltjx.jeeves.vip/home/api?type=ys&uid=568259&key=aehilnrCDEFHJPTXY8&url="},
{"name":"LTjiexi2","url":"https://che.kmys.top/1.php?url="},
{"name":"kumao","url":"http://yry.schdd.cn:81/csjson.php?url="},
{"name":"feiyue1","url":"https://www.feiyuege.cf/v/jiexi2/?url="},
{"name":"feiyue2","url":"https://www.feiyuege.cf/v/jiexi/?url="},
{"name":"caijizhan","url":"https://api.apilyzy.com/api.php"},
{"name":"caijizhan1","url":"https://apihjzy.com/api.php"},
{"name":"caijizhan2","url":"https://apittzy.com/api.php"},
{"name":"caijizhan3","url":"https://api.xiuseapi.com/api.php"},
{"name":"caijizhan4","url":"http://api.kdapi.info/api.php"},
{"name":"caijizhan5","url":"https://siwazyw.net/api.php"},
{"name":"caijizhan6","url":"http://api.saosezy.icu/api.php"},
{"name":"wuduyunjiexi","url":"https://jf.1080p.icu:3377/home/api?type=ys&uid=139706&key=cgjlntwxzAEMQTUVWX&url="}
],

//填写电视直播的接口链接
"dianshizhibo": "http://www.mikkk.xyz/bblive.txt",

//填写播放地址过滤规则，中间用#号分割，不用填太多，默认的基本够用，主要是针对自定义的网站过滤的。
"guolvdizhi": "player.css#url=#51.la#poster#api.php#file=#auth_#cnzz.com",

//填写网页接口内容，格式是 {网页接口1},{网页接口2},{网页接口3} 一个花括号里面就是一个自定义接口内容  用，号分割  最后一个不加，号
"zidingyi": [
{"name": "唐人街",
  "url": "https://www.tangrenjie.tv/",
  "tihuan": "cnzz.com", 
  "User": "空", 
  "shouye": "1",

  "fenlei": "动作片$/vod/show/id/6/page/#喜剧片$/vod/show/id/7/page/#爱情片$/vod/show/id/8/page/#科幻片$/vod/show/id/9/page/#恐怖片$/vod/show/id/10/page/#剧情片$/vod/show/id/11/page/#战争片$/vod/show/id/12/page/#国产剧$/vod/show/id/13/page/#港台剧$/vod/show/id/14/page/#日韩剧$/vod/show/id/15/page/#欧美剧$/vod/show/id/16/page/#海外剧$/vod/show/id/27/page/#综艺$/vod/show/id/3/page/#纪录片$/vod/show/id/28/page/#动漫$/vod/show/id/4/page/",
  "houzhui": ".html",

  "shifouercijiequ": "0", 
  "jiequqian": "空",
  "jiequhou": "空", 
  "jiequshuzuqian": "class=\"vodlist_item", 
  "jiequshuzuhou": "><span",
  "tupianqian": "data-original=\"",
  "tupianhou": "\"",
  "biaotiqian": "title=\"", 
  "biaotihou": "\"",
  "lianjieqian": "href=\"", 
  "lianjiehou": "\"", 

  "sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
  "sousuohou": "&limit=500",
  "sousuohouzhui": "/voddetail/", 
  "ssmoshi": "0",
  "sousuoshifouercijiequ": "0",
  "jspic": "pic",
  "jsname": "name",
  "jsid": "id",
  "ssjiequqian": "空",
  "ssjiequhou": "空",
  "ssjiequshuzuqian": "空",
  "ssjiequshuzuhou": "空",
  "sstupianqian": "空",
  "sstupianhou": "空",
  "ssbiaotiqian": "空",
  "ssbiaotihou": "空",
  "sslianjieqian": "空",
  "sslianjiehou": "空",

  "bfshifouercijiequ": "0",
  "bfjiequqian": "空",
  "bfjiequhou": "空",
  "bfjiequshuzuqian": "id=\"playlistbox", 
  "bfjiequshuzuhou": "</div>", 

  "zhuangtaiqian": "年份：</span>",
  "zhuangtaihou": "</a>",
  "daoyanqian": "导演：</span>",
  "daoyanhou": "</a>",
  "zhuyanqian": "主演：</span>",
  "zhuyanhou": "</li>",
  "juqingqian": "剧情介绍</h2><font size=\"",
  "juqinghou": "</font>",
  "bfyshifouercijiequ": "0",
  "bfyjiequqian": "空",
  "bfyjiequhou": "空",
  "bfyjiequshuzuqian": "<a",
  "bfyjiequshuzuhou": "/a>",
  "bfbiaotiqian": ">",
  "bfbiaotihou": "<",
  "bflianjieqian": "href=\"",
  "bflianjiehou": "\""},

{"name": "钉子电影",
  "url": "https://www.dingzidy.wang/",
  "tihuan": "cnzz.com", 
  "User": "空", 
  "shouye": "1",

  "fenlei": "电影$/type/1-#电视剧$/type/2-#动漫$/type/3-#综艺$/type/4-#直播$/type/5-#音乐$/type/6-#美图$/type/7-#有声小说$/type/8-",
  "houzhui": ".html",

  "shifouercijiequ": "0", 
  "jiequqian": "空",
  "jiequhou": "空", 
  "jiequshuzuqian": "class=\"movie-item", 
  "jiequshuzuhou": "height=\"",
  "tupianqian": "src=\"",
  "tupianhou": "\"",
  "biaotiqian": "title=\"", 
  "biaotihou": "\"",
  "lianjieqian": "href=\"", 
  "lianjiehou": "\"", 

  "sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
  "sousuohou": "&limit=500",
  "sousuohouzhui": "/voddetail/", 
  "ssmoshi": "0",
  "sousuoshifouercijiequ": "0",
  "jspic": "pic",
  "jsname": "name",
  "jsid": "id",
  "ssjiequqian": "空",
  "ssjiequhou": "空",
  "ssjiequshuzuqian": "空",
  "ssjiequshuzuhou": "空",
  "sstupianqian": "空",
  "sstupianhou": "空",
  "ssbiaotiqian": "空",
  "ssbiaotihou": "空",
  "sslianjieqian": "空",
  "sslianjiehou": "空",

  "bfshifouercijiequ": "0",
  "bfjiequqian": "空",
  "bfjiequhou": "空",
  "bfjiequshuzuqian": "class=\"dslist-group-item", 
  "bfjiequshuzuhou": "</div>", 

  "zhuangtaiqian": "上映时间</span></td> <td>",
  "zhuangtaihou": "</td>",
  "daoyanqian": "导演</span></td>",
  "daoyanhou": "</td>",
  "zhuyanqian": "主演</span></td>",
  "zhuyanhou": "</td>",
  "juqingqian": "剧情介绍：</strong></p>",
  "juqinghou": "</p>",
  "bfyshifouercijiequ": "0",
  "bfyjiequqian": "空",
  "bfyjiequhou": "空",
  "bfyjiequshuzuqian": "<a",
  "bfyjiequshuzuhou": "/a>",
  "bfbiaotiqian": ">",
  "bfbiaotihou": "<",
  "bflianjieqian": "href=\"",
  "bflianjiehou": "\""},
  
{"name": "欧乐影院",
  "url": "https://oulevod.tv/",
  "tihuan": "cnzz.com", 
  "User": "空", 
  "shouye": "1",

  "fenlei": "国产电影$/index.php/vod/show/id/1/lang/国语/page/#欧美电影$/index.php/vod/show/id/1/lang/英语/page/#港台电影$/index.php/vod/show/id/1/lang/粤语/page/#韩国电影$/index.php/vod/show/id/1/lang/韩语/page/#日本电影$/index.php/vod/show/id/1/lang/日语/page/#其他电影$/index.php/vod/show/id/1/lang/其它/page/#国产剧$/index.php/vod/show/id/2/lang/国语/page/#欧美剧$/index.php/vod/show/id/2/lang/英语/page/#港台剧$/index.php/vod/show/id/2/lang/粤语/page/#韩国剧$/index.php/vod/show/id/2/lang/韩语/page/#日本剧$/index.php/vod/show/id/2/lang/日语/page/#其他剧$/index.php/vod/show/id/2/lang/其它/page/#国产动漫$/index.php/vod/show/id/3/lang/国语/page/#欧美动漫$/index.php/vod/show/id/3/lang/英语/page/#港台动漫$/index.php/vod/show/id/3/lang/粤语/page/#韩国动漫$/index.php/vod/show/id/3/lang/韩语/page/#日本动漫$/index.php/vod/show/id/3/lang/日语/page/#其他动漫$/index.php/vod/show/id/3/lang/其它/page/#国产综艺$/index.php/vod/show/id/4/lang/国语/page/#欧美综艺$/index.php/vod/show/id/4/lang/英语/page/#港台综艺$/index.php/vod/show/id/4/lang/粤语/page/#韩国综艺$/index.php/vod/show/id/4/lang/韩语/page/#日本综艺$/index.php/vod/show/id/4/lang/日语/page/#其他综艺$/index.php/vod/show/id/4/lang/其它/page/#体育$/index.php/vod/show/id/50/page/#纪录片$/index.php/vod/show/id/50/page/",
  "houzhui": ".html",

  "shifouercijiequ": "0", 
  "jiequqian": "空",
  "jiequhou": "空", 
  "jiequshuzuqian": "class=\"hl-item-thumb", 
  "jiequshuzuhou": "<div",
  "tupianqian": "data-original=\"",
  "tupianhou": "\"",
  "biaotiqian": "title=\"", 
  "biaotihou": "\"",
  "lianjieqian": "href=\"", 
  "lianjiehou": "\"", 

  "sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
  "sousuohou": "&limit=500",
  "sousuohouzhui": "/voddetail/", 
  "ssmoshi": "0",
  "sousuoshifouercijiequ": "0",
  "jspic": "pic",
  "jsname": "name",
  "jsid": "id",
  "ssjiequqian": "空",
  "ssjiequhou": "空",
  "ssjiequshuzuqian": "空",
  "ssjiequshuzuhou": "空",
  "sstupianqian": "空",
  "sstupianhou": "空",
  "ssbiaotiqian": "空",
  "ssbiaotihou": "空",
  "sslianjieqian": "空",
  "sslianjiehou": "空",

  "bfshifouercijiequ": "0",
  "bfjiequqian": "空",
  "bfjiequhou": "空",
  "bfjiequshuzuqian": "id=\"hl-plays-list", 
  "bfjiequshuzuhou": "</div>", 

  "zhuangtaiqian": "状态：</span>",
  "zhuangtaihou": "</p>",
  "daoyanqian": "导演：</span>",
  "daoyanhou": "</p>",
  "zhuyanqian": "主演：</span>",
  "zhuyanhou": "</p>",
  "juqingqian": "简介：</em>",
  "juqinghou": "</li>",
  "bfyshifouercijiequ": "0",
  "bfyjiequqian": "空",
  "bfyjiequhou": "空",
  "bfyjiequshuzuqian": "<a",
  "bfyjiequshuzuhou": "/a>",
  "bfbiaotiqian": ">",
  "bfbiaotihou": "<",
  "bflianjieqian": "href=\"",
  "bflianjiehou": "\""},

{"name": "团夕影视",
  "url": "https://www.kan365.xyz",
  "tihuan": "cnzz.com", 
  "User": "空", 
  "shouye": "1",

  "fenlei": "电影$/index.php/vod/show/id/1/page/#连续剧$/index.php/vod/show/id/2/page/#综艺$/index.php/vod/show/id/3/page/#动漫$/index.php/vod/show/id/4/page/",
  "houzhui": ".html",

  "shifouercijiequ": "0", 
  "jiequqian": "空",
  "jiequhou": "空", 
  "jiequshuzuqian": "class=\"vodlist_thumb", 
  "jiequshuzuhou": "<span",
  "tupianqian": "data-original=\"",
  "tupianhou": "\"",
  "biaotiqian": "title=\"", 
  "biaotihou": "\"",
  "lianjieqian": "href=\"", 
  "lianjiehou": "\"", 

  "sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
  "sousuohou": "&limit=500",
  "sousuohouzhui": "/voddetail/", 
  "ssmoshi": "0",
  "sousuoshifouercijiequ": "0",
  "jspic": "pic",
  "jsname": "name",
  "jsid": "id",
  "ssjiequqian": "空",
  "ssjiequhou": "空",
  "ssjiequshuzuqian": "空",
  "ssjiequshuzuhou": "空",
  "sstupianqian": "空",
  "sstupianhou": "空",
  "ssbiaotiqian": "空",
  "ssbiaotihou": "空",
  "sslianjieqian": "空",
  "sslianjiehou": "空",

  "bfshifouercijiequ": "0",
  "bfjiequqian": "空",
  "bfjiequhou": "空",
  //"bfjiequshuzuqian": "class=\"content_playlist list", 
  "bfjiequshuzuqian": "id=\"playlistbox", 
  "bfjiequshuzuhou": "</div>", 

  "zhuangtaiqian": "状态：</span>",
  "zhuangtaihou": "</p>",
  "daoyanqian": "导演：</span>",
  "daoyanhou": "</p>",
  "zhuyanqian": "主演：</span>",
  "zhuyanhou": "</p>",
  "juqingqian": "<h1>",
  "juqinghou": "</h1>",
  "bfyshifouercijiequ": "0",
  "bfyjiequqian": "空",
  "bfyjiequhou": "空",
  "bfyjiequshuzuqian": "<a",
  "bfyjiequshuzuhou": "/a>",
  "bfbiaotiqian": ">",
  "bfbiaotihou": "<",
  "bflianjieqian": "href=\"",
  "bflianjiehou": "\""}

]
}